config/routes.rb
WebGeek::Application.routes.draw do

  root :to => 'pages#index'

  get 'signin' => "sessions#new"

  post 'signin' => "sessions#create", :as => 'signin_post'

  get 'signout' =>  "sessions#destroy"

  post 'search' => "victims#search", :as => 'search_victims'
  
  get 'donations' => "pages#donations", :as => 'donations'
  
  resources :shelters

  resources :victims

  resources :supplies

end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
  attr_accessible :name, :address, :capacity, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode
  has_many :victims

  validates_presence_of :name, :maximum => 255

  validates_presence_of :address, :maximum => 255

  validates_presence_of :capacity
  validates_numericality_of :capacity, :greater_than => 0, :less_than => 50000, :only_integer => true

  def to_label
    address
  end

  def capacity_in_percent
    (victims_count / capacity.to_f) * 100
  end

end

app/models/supply.rb
class Supply < ActiveRecord::Base
  attr_accessible :quantity, :shelter_id, :code
  belongs_to :shelter


  def get_the_type
    case code
    when 1
      "Food"
    when 2
      "Water"
    when 3
      "First Aid Kit"
    else
      "Bananas"
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :contact, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/models/victim.rb
class Victim < ActiveRecord::Base
  belongs_to :shelter, :counter_cache => true
  belongs_to :user
  attr_accessible :age, :description, :name, :shelter_id, :status, :user_id

  validates_presence_of :name, :maximum => 255

  validates_presence_of :age
  validates_numericality_of :age, :greater_than => 0, :less_than => 120, :only_integer => true

  CRITICAL = 1
  SICK  = 2
  ALIVE = 3
  DECEASED = 4

  scope :name_like, lambda { |victim_name|
    { :conditions => ["name ~* ?", victim_name] }
  }

  def to_status
    case self.status
    when CRITICAL
      "Critical"
    when SICK
      "Sick"
    when ALIVE
      "Alive"
    when DECEASED
      "Deceased"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def donations
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You are now signed in!"
      redirect_to root_url
    else
      flash.now[:danger] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = "Logged out!"
    redirect_to root_url
  end

end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  def index
    @shelter = Shelter.new
    @shelters = Shelter.all
  end

  def show
    @shelter = Shelter.find_by_id(params['id'])
  end

  def new
    @shelter = Shelter.new
  end

  def edit
  end
  
  def create
    @shelter = Shelter.new(params[:shelter])
    if @shelter.save
      redirect_to @shelter,
        :notice => "Shelter was successfully created."
    else
      render action: "new"
    end
  end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  def index
  end

  def new
    @supply = Supply.new
    @shelters = Shelter.all
  end

  def show
    @supply = Supply.find_by_id(params[:id])
  end

  def create
    @supply = Supply.new(params[:supply])
    if @supply.save
      redirect_to @supply,
        :notice => "#{@supplyname} was successfully created."
    else
      render aciton: "new"
    end

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/victims_controller.rb
class VictimsController < ApplicationController
  def index
    @victims = Victim.all
    @victim = Victim.new
    @shelters = Shelter.all
  end

  def show
    @victim = Victim.find_by_id(params[:id])
  end

  def new
    @victim = Victim.new
    @shelters = Shelter.all
  end

  def edit
  end

  def create
    @victim = Victim.new(params[:victim])
    @victim.user_id = current_user.id
    if @victim.save
      redirect_to victims_path,
        :notice => "#{@victim.name} was successfully created."
    else
      render action: "new"
    end
  end

  def search
    @victims = Victim.name_like(params[:name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
   current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def nav_link(link_text, link_path, controller = '')
    class_name = ''
    if controller.blank?
      class_name = current_page?(link_path) ? 'active' : ''
    else
      class_name = (params[:controller] == controller) ? 'active' : ''
    end
    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
  
  def row_clickable
    return "location.href = this.getElementsByTagName('a').item(0).getAttribute('href');"
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/victims_helper.rb
module VictimsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= "Webgeek"
    %meta{:name => "viewport", "content" => "width=device-width, initial-scale=1.0"}
    = javascript_include_tag "application"
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCfLi7uzxlL7Lrm1lnO7O7dWQHdgfl_2Lk&sensor=false&libraries=places"

    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

    = stylesheet_link_tag "application", :media => "all"
    / Le fav and touch icons
    =# %link{:href => "/images/favicon.ico", :rel => "shortcut icon"}/
    =# %link{:href => "/images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    =# %link{:href => "/images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    =# %link{:href => "/images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/

    - current_path = request.env['PATH_INFO']
    - container_div_class = "index-search-bg" if current_path == root_path
  %body{ :class => container_div_class }
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar.collapsed{"data-toggle" => "collapse", "data-target" => ".nav-collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => root_path}
            %b 
              %span.red-text Sagip
          .nav-collapse.collapse{:style => "height: 0px;  "}
            %ul.nav
              = nav_link "Home", root_path
              = nav_link "Victims", victims_path
              = nav_link "Evac Shelters", shelters_path
              = nav_link "Donations", donations_path
              
            -if current_user.blank?
              %a.block.pull-right.btn.btn-danger{:href => signin_path}
                Volunteer Login
            -else
              %a.block.pull-right.btn.btn-inverse{:href => signout_path}
                Logout
    %div
      .container
        .content
          - flash.each do |key, value|
            %div.alert.fade.in{:class => "alert alert-#{key}", 'data-alert' => "alert"}
              =#%a.close{:href => '#', 'data-dismiss' => "alert"} &times;
              = value
          = yield

= javascript_include_tag controller_name

app/views/pages/donations.html.haml
.hero-unit
  %h2 This page will be for charity organizations and disaster groups

app/views/pages/index.html.haml
= javascript_include_tag "index.maps"

.row-fluid
  .span3
    .modal{:style => "position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; width:100%;"}
      .modal-header
        %h4 Search a name
      .modal-footer
        %form.simple_form{:method => "post", :action => search_victims_path}
          %input.span12{:type => "text", :name => "name", :size => "50", :placeholder => "Juan Dela Cruz" }
          %input.span12.btn.btn-info{:type => "submit", :value => "Look for this person"}
    .modal{:style => "position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; width:100%;"}
      .modal-header
        %h5 Hotlines
      .modal-footer
        %table.table.table-condensed
          %tr
            %td
              %b NDRRMC
            %td.placeholder
              (02) 911-1406
              %br
              (02) 912-2665
          %tr
            %td
              %b REDCROSS
            %td.placeholder
              143
              %br
              (02) 911-1876
          %tr
            %td
              %b PNP
            %td.placeholder
              711
              %br
              TXT PNP to 2920
        
    
  .span9
    .modal{:style => "position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; width:100%;"}
      .modal-header
        %h4.red-text Evacuation Centers
        = content_tag "div", id: "shelters", :style =>"display:none", data: {shelters: Shelter.all} do
          &nbsp
      .modal-body{:style => "padding:0px"}
        #map_canvas{:style => "height: 400px; width: 100%"}
      .modal-footer
        .placeholder These are the locations of our evacuation centers

%hr
.row-fluid
  .span6
    %h4.red-text News
    %div#myCarousel.carousel.slide
      %div.carousel-inner
        %div.active.item
          = image_tag "flood1.jpeg"
          %div.carousel-caption
            %h4
              Waist Deep Floods are abound in the area.
            %p
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et
        %div.item
          = image_tag "flood2.jpeg"
          %div.carousel-caption
            %h4 Lorem ipsum dolor sit amet, consectetuer adipiscing
            %p
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et
        %div.item
          = image_tag "flood3.jpeg"
          %div.carousel-caption
            %h4 Lorem ipsum dolor sit amet, consectetuer adipiscing
            %p
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et
        %div.item
          = image_tag "flood4.jpeg"
          %div.carousel-caption
            %h4 Lorem ipsum dolor sit amet, consectetuer adipiscing
            %p
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et
      %a.carousel-control.left{:href => "#myCarousel", "data-slide"=>"prev", "data-interval"=>2000} &lsaquo;
      %a.carousel-control.right{:href=>"#myCarousel", "data-slide"=>"next", "data-interval"=>2000} &rsaquo;
  .span6
    %h4 Twitter Feed
    .hero-unit
      %h2 Twitter Feed Here
    

app/views/shelters/_form.html.haml
= simple_form_for @shelter do |f|
  .placeholder Name
  = f.input :name, :label => false, :placeholder => "Name of center"
  .placeholder Address
  = f.input :address, :label => false
  .placeholder Capacity
  = f.input :capacity, :label => false, :placeholder => "(e.g. 500000)"
  = f.button :submit, :class => "btn btn-info"
= javascript_include_tag "autocomplete"

app/views/shelters/_view.html.haml
.modal{:style => "position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; width:100%;"}
  .modal-header
    %h4.red-text Evacuation Centers
  .modal-body{:style => "padding:0px"}
    %table.table
      %th Name
      %th Address
      %th Capacity
      - shelters.each do |shelter|
        %tr.selectable{:onclick => row_clickable}
          %td
            = link_to "", shelter_path(shelter)
            = shelter.name
          %td= shelter.address
          %td= shelter.capacity
  .modal-footer
    .placeholder These are the locations of our evacuation centers

app/views/shelters/index.html.haml
.row-fluid
  - unless current_user.nil?
    .span3
      %h4 Add Shelter
      = render "form"
    .span9
      = render :partial => "view", :locals => {:shelters => @shelters }
  - else
    .span12
      = render :partial => "view", :locals => {:shelters => @shelters }

app/views/shelters/show.html.haml
= javascript_include_tag "maps"

%div#address{:style => "display:none"}
  = "#{@shelter.latitude}, #{@shelter.longitude}"

.row-fluid
  .span6
    .modal{:style => "position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; width:100%;"}
      .modal-header
        %b= @shelter.name
        .placeholder= @shelter.address
          
      .modal-body{:style => "padding:0px"}
        #map_canvas{:style => "height: 300px; width: 100%"}

  .span6
    .modal{:style => "position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; width:100%;"}
      .modal-header
        %h5 Shelter Population
      .modal-footer
        %table.table.table-condensed
          %tr
            %td
              %b Status
            %td
              %p
                = "This shelter is #{@shelter.capacity_in_percent}% full!"
          %tr
            %td
              %b Total Capacity
            %td
              ="#{@shelter.capacity}"
          

    

app/views/supplies/_form.html.haml
= simple_form_for @supply do |f|
  = f.input :code, :include_blank => false, :collection => { "Food" => 1, "Water" => 2, "First Aid Kit" => 3 }

  = f.input :quantity, :include_blank => false, :collection => 1..32

  = f.association :shelter, :include_blank => false

  = f.button :submit

app/views/supplies/new.html.haml
= render "form"

app/views/supplies/show.html.haml
= @supply.get_the_type
= @supply.quantity

app/views/victims/_form.html.haml
= simple_form_for @victim do |f|
  .placeholder Name
  = f.input :name, :label => false, :input_html => {:class => 'span12', :placeholder => "Juan Dela Cruz"}
  .placeholder Age
  = f.input :age, :label => false, :input_html => {:class => 'span12', :placeholder => ""}
  .placeholder Status
  = f.input :status, :label => false, :include_blank => false, :collection => { :ALIVE => 3, :SICK => 2, :CRITICAL => 1, :DECEASED => 4 }, :input_html => {:class => 'span12'}
  .placeholder Description
  = f.input :description, :label => false, :input_html => {:class => 'span12', :rows => 3, :placeholder => "Write description here..."}
  .placeholder Shelter
  = f.association :shelter, :label => false, :include_blank => false, :input_html => {:class => 'span12'}

  = f.button :submit

app/views/victims/_view.html.haml
.modal{:style => "position: relative; top: auto; left: auto; margin: 0 auto 20px; z-index: 1; width:100%;"}
  .modal-header
    %h4.red-text Victims
  .modal-body{:style => "padding:0px"}
    %table.table
      %th Name
      %th Age
      %th Description
      %th Shelter
      %th Status
      - victims.each do |victim|
        %tr.selectable{:onclick => row_clickable}
          %td
            = link_to "", victim_path(victim)
            = victim.name
          %td= victim.age
          %td= victim.description
          %td= victim.shelter.name
          %td= victim.to_status
  .modal-footer
    .placeholder These are the locations of our evacuation centers

app/views/victims/index.html.haml
.row-fluid
  - unless current_user.nil?
    .span3
      %h4 Add a victim
      = render "form"
    .span9
      = render :partial => "view", :locals => { :victims => @victims }
  - else
    .span12
      = render :partial => "view", :locals => { :victims => @victims }

app/views/victims/search.html.haml
.row-fluid
  .span3
    %h5 Search a name
    %form.simple_form{:method => "post", :action => search_victims_path}
      %input.span12{:type => "text", :name => "name", :size => "50", :placeholder => "Juan Dela Cruz" }
      %input.span12.btn.btn-info{:type => "submit", :value => "Look for this person"}
  .span9
    %h5.red-text Search Results
    - if !@victims.empty?
      %table.table
        %thead
          %th Name
          %th Age
          %th Description
          %th Shelter
          %th Status
        %tbody
          - @victims.each do |victim|
            %tr
              %td
                = victim.name
              %td
                = victim.age
              %td
                = victim.description
              %td
                = victim.shelter.name
              %td
                = victim.to_status
    -else
      .placeholder= "Sorry that person cannot be found on our list"

app/views/victims/show.html.haml
= @victim.name
= @victim.age
= @victim.status
= @victim.description